apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: store-frontend # <-- Обрати внимание, неймспейс совпадает с Deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2   # Как только HPA запустится, он сразу сделает 2 пода для надежности
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Скейлимся, если загрузка CPU превысит 70% от запрошенных 50m
